FROM eclipse-temurin:17-jdk

WORKDIR /app

# JAR만 복사
COPY build/libs/*.jar app.jar

ENV TZ=Asia/Seoul

EXPOSE 4000

ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar", "app.jar", "--spring.profiles.active=docker"]
