# 1) 빌드 단계
FROM node:22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

# 🔥 이 부분만 수정하면 됨
COPY . .
COPY .env.local ./.env.local

RUN npm run build

# Run 단계
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
